CREATE TABLE Administrador (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100) NOT NULL,
  cpf VARCHAR2(14) NOT NULL UNIQUE,
  senha VARCHAR2(100) NOT NULL,
  cargo VARCHAR2(30) NOT NULL
);
